# note: yaml extend syntax can be used
# .base: &base
#   param: value

PROD_HOST:
  # <<: *base
  stage: production
  user: PROD_USER

STAGING_HOST:
  # <<: *base
  stage: staging
  user: STAGING_USER
